name: Apps Script CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  environment: production
  deploy-apps-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: daikikatsuragawa/clasp-action@v1.0.1
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ secrets.SCRIPT_ID }}
          command: "push"
